name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # 毎日JST午前9時に実行
  workflow_dispatch: # 手動実行ボタンを出せるようにする

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      # 1. 最新の安定版（v4）でリポジトリを読み込む
      - uses: actions/checkout@v4

      # 2. 蛇のアニメーション画像を生成する
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. 履歴を汚さないために「output」という専用の隠しブランチに保存する
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}